name: Publish VSCode extension

# # Only trigger when a new release is released
# # see: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
# on:
#   release:
#     types: [published]

# trigger manually for now
on:
  - workflow_dispatch
  - push

jobs:
  release:
    runs-on: ubuntu-latest
    environment: deploy-vsce-prod
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
    - name: Install vsce
      run: npm install -g @vscode/vsce
    - name: Bundle
      run: 
        npm run compile
    - name: VSCE package and publish
      env:
        # see docs: https://code.visualstudio.com/api/working-with-extensions/continuous-integration#github-actions-automated-publishing
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
      run: |
        vsce package
        vsce publish