name: Publish VSCode extension

on:
  push:
    tags:
      # Using '**' instead of '*' here to match all tags: https://stackoverflow.com/a/61892639/530728
      - '**'

jobs:
  release:
    runs-on: ubuntu-latest
    environment: deploy-vsce-prod
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
    - name: Install vsce
      run: npm install -g @vscode/vsce
    - name: Bundle
      run: 
        npm run compile
    - name: VSCE package and publish
      env:
        # see docs: https://code.visualstudio.com/api/working-with-extensions/continuous-integration#github-actions-automated-publishing
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
      run: |
        vsce package
        vsce publish